#!/usr/bin/env bash
# scripts/demo/setup_testnet_env.sh
# Generate testnet credentials for real transaction recording
# Usage: bash scripts/demo/setup_testnet_env.sh

set -euo pipefail

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Sui-Nexus Testnet Environment Setup"
echo "══════════════════════════════════════════════════════"
echo ""

# Detect sui binary
SUI_BIN=""
for p in "/opt/homebrew/bin/sui" "/usr/local/bin/sui" "$HOME/go/bin/sui"; do
  if [ -x "$p" ]; then SUI_BIN="$p"; break; fi
done
if [ -z "$SUI_BIN" ]; then
  echo "ERROR: sui CLI not found. Install with: arch -arm64 brew install sui"
  exit 1
fi
echo "  Sui CLI: $SUI_BIN"

# Detect active address
ACTIVE_ADDR=$($SUI_BIN client active-address 2>/dev/null || echo "")
if [ -z "$ACTIVE_ADDR" ]; then
  echo "ERROR: No active Sui address."
  exit 1
fi
echo "  Active address: $ACTIVE_ADDR"

# Get gas coin
GAS_COIN=""
GAS_OUT=$($SUI_BIN client gas --json 2>/dev/null || echo "[]")
for coin_id in $($SUI_BIN client gas --json 2>/dev/null | python3 -c "import sys,json;d=json.load(sys.stdin);print('\n'.join(c.get('gasCoinId','') for c in (d if isinstance(d,list) else d.get('data',[]))))" 2>/dev/null || true); do
  GAS_COIN=$coin_id
  break
done
if [ -z "$GAS_COIN" ]; then
  echo "ERROR: No gas coin found."
  exit 1
fi
echo "  Gas coin: $GAS_COIN"

# Get private key
PRIVATE_KEY=$($SUI_BIN keytool export --key-identity "$ACTIVE_ADDR" --json 2>/dev/null | \
  python3 -c "import sys,json;print(json.load(sys.stdin)['exportedPrivateKey'])" 2>/dev/null || echo "")
if [ -z "$PRIVATE_KEY" ]; then
  echo "ERROR: Could not export private key."
  exit 1
fi
echo "  Private key: ${PRIVATE_KEY:0:25}..."

PACKAGE_ID="0xa051bbf9517d8ee94f2339e69877e4eacec38d3f4893b0aedf84774d18c54433"

# Determine output path — write to project root or /tmp if read-only
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.testnet"
WRITE_TARGET="$ENV_FILE"

# Test if we can write to project root
if ! touch "$ENV_FILE" 2>/dev/null; then
  WRITE_TARGET="/tmp/sui-nexus-env.sh"
  echo ""
  echo "  Note: Project root is read-only. Writing to: $WRITE_TARGET"
fi

cat > "$WRITE_TARGET" << EOF
# Sui-Nexus Testnet Environment — Real Transaction Mode
# Generated by scripts/demo/setup_testnet_env.sh

export SUI_RPC_URL="https://fullnode.testnet.sui.io:443"
export SUI_SIGNER_PRIVATE_KEY="$PRIVATE_KEY"
export SUI_GAS_OBJECT_ID="$GAS_COIN"
export SUI_FUNDING_OBJECT_ID=""
export SUI_SIGNER_MNEMONIC=""
export AGENT_WALLET_PACKAGE_ID="$PACKAGE_ID"
export DEEPBOOK_PACKAGE_ID="0xdee9"
export DEEPBOOK_POOL_ID=""
export WALRUS_API_URL="https://walrus.testnet.sui.io"
export SERVER_PORT="8080"
export HMAC_SECRET_KEY="dev-secret-key-change-in-prod"
export KAFKA_BROKERS="localhost:9092"
export REDIS_ADDR="localhost:6379"
export ZKLOGIN_ENABLED="false"
export DEMO_AGENT_ADDRESS="$ACTIVE_ADDR"
export DEMO_ZKLOGIN_ADDRESS="$ACTIVE_ADDR"
export DEMO_ZKLOGIN_TOKEN="testnet-session-token"
export HACKATHON_DEMO_MODE="false"
export AGENT_WALLET_ENABLED="true"
export SUI_GAS_BUDGET="10000000"
EOF

echo ""
echo "  Written: $WRITE_TARGET"
echo ""
echo "Next steps:"
echo ""
echo "  1. Load environment:"
echo "     source $WRITE_TARGET"
echo ""
echo "  1.5 Set a dedicated funding coin:"
echo "     export SUI_FUNDING_OBJECT_ID='0x...'"
echo ""
echo "  2. Start Gateway:"
echo "     HACKATHON_DEMO_MODE=false go run cmd/gateway/main.go &"
echo "     sleep 3"
echo ""
echo "  3. Run demo:"
echo "     python3 scripts/demo/agent_wallet_demo.py"
echo ""
echo "══════════════════════════════════════════════════════"
